"""The YouTube resolver. Turns the curator's named songs into real video IDs,
filters out region-blocked / wrong-length results, prefers official sources,
then creates the PUBLIC playlists and fills the CORE list to the Engine clock.

Quota note: search.list costs 100 units; videos.list 1 unit (batched). Two
playlists/day is well within the free 10,000/day. TODO (perf phase): cache the
song -> video_id resolution so repeat songs skip the 100-unit search."""
import re

from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials

from .config import settings

SCOPES = ["https://www.googleapis.com/auth/youtube"]
_ISO = re.compile(r"PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?")


def _service():
    if not settings.youtube_refresh_token:
        raise RuntimeError(
            "No YouTube refresh token configured. Run:  python -m scripts.connect_youtube"
        )
    creds = Credentials(
        token=None,
        refresh_token=settings.youtube_refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=settings.google_client_id,
        client_secret=settings.google_client_secret,
        scopes=SCOPES,
    )
    return build("youtube", "v3", credentials=creds, cache_discovery=False)


def _iso_to_min(iso: str) -> float:
    m = _ISO.fullmatch(iso or "")
    if not m:
        return 0.0
    h, mi, s = (int(x) if x else 0 for x in m.groups())
    return h * 60 + mi + s / 60


def _official_score(channel_title: str) -> int:
    """Prefer official audio sources: 'Artist - Topic' > VEVO > 'Official' > rest."""
    ct = (channel_title or "").lower()
    if ct.endswith("- topic"):
        return 3
    if "vevo" in ct:
        return 2
    if "official" in ct:
        return 1
    return 0


def resolve_track(yt, artist: str, title: str):
    """Best official, region-OK, sane-length match -> (video_id, minutes) or None."""
    resp = yt.search().list(
        part="snippet",
        q=f"{artist} {title}",
        type="video",
        videoCategoryId="10",          # Music
        regionCode=settings.target_region,
        maxResults=5,
    ).execute()

    ids = [it["id"]["videoId"] for it in resp.get("items", [])]
    if not ids:
        return None

    meta = yt.videos().list(part="contentDetails,status,snippet", id=",".join(ids)).execute()

    candidates = []
    for v in meta.get("items", []):
        rr = v.get("contentDetails", {}).get("regionRestriction", {})
        if settings.target_region in rr.get("blocked", []):
            continue
        allowed = rr.get("allowed")
        if allowed is not None and settings.target_region not in allowed:
            continue
        mins = _iso_to_min(v["contentDetails"]["duration"])
        if mins < 1.3 or mins > 12:        # skip clips and 10-hour loops
            continue
        candidates.append((_official_score(v["snippet"]["channelTitle"]), v["id"], mins))

    if not candidates:
        return None
    candidates.sort(key=lambda c: c[0], reverse=True)
    _, vid, mins = candidates[0]
    return vid, mins


def create_playlist(yt, title: str, description: str) -> str:
    resp = yt.playlists().insert(
        part="snippet,status",
        body={
            "snippet": {"title": title, "description": description},
            "status": {"privacyStatus": "public"},   # public by design
        },
    ).execute()
    return resp["id"]


def add_to_playlist(yt, playlist_id: str, video_id: str):
    yt.playlistItems().insert(
        part="snippet",
        body={
            "snippet": {
                "playlistId": playlist_id,
                "resourceId": {"kind": "youtube#video", "videoId": video_id},
            }
        },
    ).execute()


def build_playlist(name: str, tracks, target_min: float | None):
    """Resolve tracks, create a public playlist, add those that resolve, stopping
    once the running time reaches `target_min` (used to fit the CORE to the Engine)."""
    yt = _service()
    pid = create_playlist(yt, name, "Generated by WOD2Beats")
    total = 0.0
    resolved = []
    for t in tracks:
        r = resolve_track(yt, t.artist, t.title)
        if not r:
            continue
        vid, mins = r
        add_to_playlist(yt, pid, vid)
        t.video_id = vid
        t.youtube_url = f"https://www.youtube.com/watch?v={vid}"
        t.minutes = mins
        resolved.append(t)
        total += mins
        if target_min and total >= target_min:
            break
    url = f"https://www.youtube.com/playlist?list={pid}"
    return url, resolved
